jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn -B package --file pom.xml

        '
    - continue-on-error: true
      name: Build jar
      uses: actions/upload-artifact@v3
      with:
        name: open-pdf-sign
        path: target/openpdfsign-*-jar-with-dependencies.jar
        retention-days: 30
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
